services:
  db:
    image: postgres:16-bookworm
    command: |
      postgres
        -c shared_preload_libraries=pg_stat_statements
        -c pg_stat_statements.track=all
        -c max_connections=200
        -c shared_buffers=256MB
        -c effective_cache_size=8GB
        -c work_mem=16MB
        -c maintenance_work_mem=128MB
        -c min_wal_size=128MB
        -c max_wal_size=2GB
        -c checkpoint_completion_target=0.9
        -c wal_buffers=16MB
        -c default_statistics_target=100
    shm_size: 256mb
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=ros_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd

  ply-api:
    image: gitlab.polytech.umontpellier.fr:5050/eii/cohoma/map/ply-api:latest
    restart: always
    depends_on:
      - ply-crawler
    ports:
      - 8000:5000
    volumes:
      - ./ply:/home/app/ply
      - ./ply-api/app.py:/home/app/app.py # Dev: overwrites the api file
    environment:
      - FLASK_SERVER_PORT=5000
      - GRID_CELL_SIZE=500 # in centimeters
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:5000/flask-health-check || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: flask run --host=0.0.0.0 --debug

  ply-crawler:
    image: gitlab.polytech.umontpellier.fr:5050/eii/cohoma/map/ply-crawler:latest
    restart: always
    depends_on:
      - db
    volumes:
      - ./ply/asked:/home/app/ply/asked
      - ./ply/pending:/home/app/ply/pending
      - ./ply/done:/home/app/ply/done
      - ./ply-crawler/app.py:/home/app/app.py # Dev: overwrites the python script
      - ./ply-crawler/generator.py:/home/app/generator.py # Dev: overwrites the python script
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=pwd
      - DB_HOST=localhost
      - DB_NAME=ros_db
      - DB_PORT=5432
      - GRID_CELL_SIZE=500 # in centimeters
    network_mode: host
